services:

  otel-collector:
    image: emqxecp/otelcol:test
    restart: always
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-trace-collector-config.yaml:/etc/otel-collector-config.yaml
    hostname: otel-collector
    mem_limit: 2G
    memswap_limit: 2G
    cpus: 2.0
    networks:
      emqx-net:
        ipv4_address: 172.19.0.10 # 4317
    depends_on:
      - datalayers

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      emqx-net:
        ipv4_address: 172.19.0.19
    depends_on:
      - datalayers

  datalayers:
    image: datalayers/datalayers:v2.2.3
    container_name: datalayers
    restart: always
    hostname: datalayers
    volumes:
      - ./datalayers-data:/var/lib/datalayers
    networks:
      emqx-net:
        ipv4_address: 172.19.0.30

  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    container_name: jaeger
    restart: always
    mem_limit: 8G
    memswap_limit: 8G
    cpus: 4.0
    ports:
      - 16686:16686
    networks:
      emqx-net:
        ipv4_address: 172.19.0.21

  emqx1:
    image: emqx/emqx-enterprise:5.8.1-g71757287
    container_name: emqx1
    restart: always
    hostname: emqx1-cluster.emqx.io
    volumes:
      - ./emqx1-data:/opt/emqx/data
    networks:
      emqx-net:
        ipv4_address: 172.19.0.2
    environment:
      - EMQX_NODE__NAME=emqx1@emqx1-cluster.emqx.io
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_LOG__CONSOLE__LEVEL=error
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=public123
      - EMQX_OPENTELEMETRY__EXPORTER__ENDPOINT="http://otel-collector:4317"
      - EMQX_OPENTELEMETRY__TRACES__ENABLE=true
      - EMQX_OPENTELEMETRY__TRACES__FILTER__TRACE_ALL=true
      - EMQX_CLUSTER__STATIC__SEEDS=emqx1@emqx1-cluster.emqx.io,emqx2@emqx2-cluster.emqx.io
    mem_limit: 8G
    memswap_limit: 8G
    cpus: 4.0
    depends_on:
      - otel-collector

  emqx2:
    image: emqx/emqx-enterprise:5.8.1-g71757287
    container_name: emqx2
    restart: always
    hostname: emqx2-cluster.emqx.io
    volumes:
      - ./emqx2-data:/opt/emqx/data
    networks:
      emqx-net:
        ipv4_address: 172.19.0.3
    environment:
      - EMQX_NODE__NAME=emqx2@emqx2-cluster.emqx.io
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_LOG__CONSOLE__LEVEL=error
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=public123
      - EMQX_OPENTELEMETRY__EXPORTER__ENDPOINT="http://otel-collector:4317"
      - EMQX_OPENTELEMETRY__TRACES__ENABLE=true
      - EMQX_OPENTELEMETRY__TRACES__FILTER__TRACE_ALL=true
      - EMQX_CLUSTER__STATIC__SEEDS=emqx1@emqx1-cluster.emqx.io,emqx2@emqx2-cluster.emqx.io
    mem_limit: 8G
    memswap_limit: 8G
    cpus: 4.0
    depends_on:
      - otel-collector

networks:
  emqx-net:
    ipam:
      config:
        - subnet: 172.19.0.0/16
    driver: bridge
