receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 33554432
      http:
        endpoint: 0.0.0.0:4318

exporters:
  datalayers:
    endpoint: http://datalayers:8361
    db: mydb
    username: admin
    password: public
    payload_max_bytes: 2000000
    metrics_schema: telegraf-prometheus-v1
    timeout: 10s
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_elapsed_time: 10s
      max_interval: 3s
    sending_queue:
      enabled: true
      num_consumers: 3
      queue_size: 1000
    trace:
      table: spans
      span_dimensions:
      - service.name
      - span_id
      - trace_id
      span_fields:
      - span.mytype
      custom_key_scope: name
      custom:
      - key:
        - client.connect
        - client.authn
        - client.authz
        - client.connack
        - client.subscribe
        - client.unsubscribe
        - client.disconnect
        - broker.subscribe
        - broker.unsubscribe
        - broker.disconnect
        table: client_events
        span_dimensions:
        - client.clientid
        - cluster.id
        - span.name
        span_fields:
        - service.name
        - service.instance.id
        - client.subscribe.topics
        - client.subscribe.sub_opts
        - client.unsubscribe.topics
        - client.connect.authn.result
        - authz.subscribe.topics
        - authz.subscribe.result
        - authz.subscribe.reason_codes
        - authz.publish.result

      - key:
        - client.publish
        - message.route
        - message.forward
        - message.handle_forward
        - broker.publish
        - client.puback
        - client.pubrec
        - client.pubrel
        - client.pubcomp
        - broker.puback
        - broker.pubrec
        - broker.pubrel
        - broker.pubcomp
        table: message_events
        span_dimensions:
        - client.clientid
        - cluster.id
        - span.name
        span_fields:
        - service.name
        - service.instance.id
        - message.from
        - message.topic
        - message.msgid

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:
  resource:
    attributes:
      - key: 'otel.library.name'
        action: delete
      - key: 'otel.library.version'
        action: delete
      - key: 'otel.scope.name'
        action: delete
      - key: 'otel.scope.version'
        action: delete
      - key: 'process.executable.name'
        action: delete
      - key: 'process.runtime.description'
        action: delete
      - key: 'process.runtime.name'
        action: delete
      - key: 'process.runtime.version'
        action: delete
      - key: 'telemetry.sdk.language'
        action: delete
      - key: 'telemetry.sdk.name'
        action: delete
      - key: 'telemetry.sdk.version'
        action: delete

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [datalayers, otlp]
