receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  datalayers:
    endpoint: http://nginx:8086
    db: mydb
    username: admin
    password: public
    timeout: 500ms
    trace:
      table: spans
      span_dimensions:
      - service.name
      - trace_id
      span_fields: []
      custom_key_scope: name
      custom:
      - key:
        - client.connect
        - client.authn
        - client.authz
        - client.connack
        - client.subscribe
        - client.unsubscribe
        - client.disconnect
        table: client_events 
        span_dimensions:
        - client.clientid
        span_fields:
        - service.instance.id
        - client.subscribe.topics
        - client.unsubscribe.topics
        - client.connect.authn.result
        - authz.subscribe.result
        - authz.publish.result

      - key:
        - client.publish
        - message.route
        - message.dispatch
        - message.deliver
        - message.forward
        - message.handle_forward
        table: message_events
        span_dimensions:
        - message.topic
        span_fields:
        - message.from
        - client.clientid
        - service.instance.id

      - key:
        - client.puback
        - client.pubrec
        - client.pubrel
        - client.pubcomp
        - emqx.puback
        - emqx.pubrec
        - emqx.pubrel
        - emqx.pubcomp
        table: todo_events
        span_dimensions:
        - service.name
        - trace_id
        span_fields:
        - attr1

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:
  resource:
    attributes:
      - key: 'otel.library.name'
        action: delete
      - key: 'otel.library.version'
        action: delete
      - key: 'process.executable.name'
        action: delete
      - key: 'process.runtime.description'
        action: delete
      - key: 'process.runtime.name'
        action: delete
      - key: 'process.runtime.version'
        action: delete
      - key: 'telemetry.sdk.language'
        action: delete
      - key: 'telemetry.sdk.name'
        action: delete
      - key: 'telemetry.sdk.version'
        action: delete


extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [datalayers, otlp]
