receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        auth:
          authenticator: basicauth/server
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: emqx

  debug:
    verbosity: detailed

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:
  resource:
    attributes:
      - key: 'otel.library.name'
        action: delete
      - key: 'otel.library.version'
        action: delete
      - key: 'otel.scope.name'
        action: delete
      - key: 'otel.scope.version'
        action: delete
      - key: 'process.executable.name'
        action: delete
      - key: 'process.runtime.description'
        action: delete
      - key: 'process.runtime.name'
        action: delete
      - key: 'process.runtime.version'
        action: delete
      - key: 'telemetry.sdk.language'
        action: delete
      - key: 'telemetry.sdk.name'
        action: delete
      - key: 'telemetry.sdk.version'
        action: delete

extensions:
  health_check:

  basicauth/server:
    htpasswd:
      inline: |
        admin:public

service:
  extensions: [health_check, basicauth/server]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    metrics/2:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
